version: "3"
services:
    db:
        image: postgres
        volumes:
            - app_db:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: test
            POSTGRES_DB: test
            POSTGRES_PASSWORD: test
        networks:
            - db-net
    app:
        build: .
        image: app
        networks:
            - db-net
            - app-net
        depends_on:
            - db
    gateway:
        image: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - app
        networks:
            - app-net
        ports:
            - 5000:5000
volumes:
    app_db:

networks:
    db-net:
    app-net:


